teams: teams.pl
	swipl -quiet -O -g main --stand_alone=true -o teams -c teams.pl

events: events.pl
	swipl -quiet -O -g main --stand_alone=true -o events -c events.pl
bus: bus.pl
	swipl -quiet -O -g main --stand_alone=true -o bus -c  bus.pl
